# Tensor Operation & Autograd Engine

In [5]:
import torch

t1 = torch.zeros(2,3)
print(t1)
print(t1.shape) #shape를 맞춰주는 것은 매우 중요 다 행렬 계산이기 때문에
print(t1.dtype) #dtype도 맞춰줘야하는 경우 존재
print(t1.device) # GPU를 사용할 수 있기때문에 연산이 이루어지는 device와 동일한 device로 넣어줘야함

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
torch.int64
cpu


In [6]:
t2 = torch.arange(4) #무조건 1차원
print(t2)
print(t2.shape)
print(t2.dtype)
print(t2.device)

tensor([0, 1, 2, 3])
torch.Size([4])
torch.int64
cpu


In [7]:
t3 = torch.rand(2,2)
print(t3)
print(t3.shape)
print(t3.dtype)
print(t3.device)

tensor([[0.0162, 0.5989],
        [0.4638, 0.2383]])
torch.Size([2, 2])
torch.float32
cpu


In [ ]:
# t() 는 tensor를 cpu에서 gpu로 보내줌, datatype을 바꿔주기도함