In [3]:
import numpy as np
import pandas as pd

In [6]:
data = {'X1':[34,25,30,38,44,48,52,60,34,34],
     'X2':[5,5,2,20,12,18,22,19,18,22],
     'Y': [5.0,2.5,4.0,3.0,3.3,4.2,4.6,6.0,3.0,2.9]
    }

In [7]:
df =pd.DataFrame(data)

In [9]:
data_np = df.values

In [10]:
data_np

array([[34. ,  5. ,  5. ],
       [25. ,  5. ,  2.5],
       [30. ,  2. ,  4. ],
       [38. , 20. ,  3. ],
       [44. , 12. ,  3.3],
       [48. , 18. ,  4.2],
       [52. , 22. ,  4.6],
       [60. , 19. ,  6. ],
       [34. , 18. ,  3. ],
       [34. , 22. ,  2.9]])

In [14]:
X = data_np[:,:-1]

In [12]:
# X = np.insert(data_np[:,:-1], 0 , np.ones(10), axis=1) d
#안해줘도 됨

In [15]:
X

array([[34.,  5.],
       [25.,  5.],
       [30.,  2.],
       [38., 20.],
       [44., 12.],
       [48., 18.],
       [52., 22.],
       [60., 19.],
       [34., 18.],
       [34., 22.]])

In [16]:
from sklearn.preprocessing import StandardScaler #보통 신경망 모형을 사용할 때 Scaling 작업을 해줌 여기서는 간단하게 StandardScalar를 사용
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [17]:
X

array([[-0.57281553, -1.27733275],
       [-1.44660194, -1.27733275],
       [-0.96116505, -1.68937557],
       [-0.18446602,  0.78288136],
       [ 0.39805825, -0.3158995 ],
       [ 0.78640777,  0.50818615],
       [ 1.17475728,  1.05757658],
       [ 1.95145631,  0.64553375],
       [-0.57281553,  0.50818615],
       [-0.57281553,  1.05757658]])

In [18]:
w_layer1 = np.random.rand(2,2) #uniform distribution를 사용해 초기화함  uniform distribution 이란 0~1 사이의 값을 가질 확률이 동일한 분포
#처음 가중치 값은 random하게 임의의 값을 설정 

In [19]:
w_layer1

array([[0.76671047, 0.41550333],
       [0.65294926, 0.68140036]])

In [20]:
b = np.random.rand(1,2)  #편향에대한 벡터 생성 여기서도 간단하게 uniform distribution 사용

In [21]:
b

array([[0.33831462, 0.94215566]])

In [22]:
H1_inputs = np.dot(X,w_layer1) + b #Hidden Layer에 들어갈 행렬 계산

In [23]:
H1_inputs #1열은 은닉노드1에 들어갈 값들 , 2열은 은닉노드2에 들어갈 값들

array([[-0.93490251, -0.16622609],
       [-1.6048437 , -0.52928725],
       [-1.50169721, -0.60835273],
       [ 0.7080644 ,  1.39896506],
       [ 0.43724371,  0.89229616],
       [ 1.27308146,  1.61518893],
       [ 1.92955717,  2.15090428],
       [ 2.25601739,  2.19285919],
       [ 0.23095073,  1.05042713],
       [ 0.5896748 ,  1.42478196]])

In [24]:
#활성화 함수(Sigmoid 함수)를 적용하기위해서 함수를 만듬
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [25]:
H1_outputs = sigmoid(H1_inputs)

In [26]:
H1_outputs # 10 X 2 행렬 생성

array([[0.28193116, 0.4585389 ],
       [0.16730573, 0.37068314],
       [0.18217253, 0.35243505],
       [0.66997332, 0.80201961],
       [0.60760207, 0.70936379],
       [0.78126979, 0.83413056],
       [0.8732004 , 0.89575325],
       [0.90516832, 0.89960643],
       [0.55748241, 0.74085691],
       [0.64329053, 0.80608698]])

In [27]:
w_layer2 = np.random.rand(2,1) #hidden layer -> output layer에서의 가중치 random하게(uniform distribution) 생성

In [28]:
w_layer2

array([[0.52711076],
       [0.51097395]])

In [29]:
b_layer2 = np.random.rand(1,1) # #hidden layer -> output layer에서의 편향 random(uniform distribution)하게 생성

In [30]:
O1_inputs = np.dot(H1_outputs,w_layer2) + b_layer2

In [31]:
O1_inputs #Output Layer에 입력하는 행렬 -> 회귀문제 예시에서는 이게 그냥 출력값 즉 y-hat

array([[0.58874433],
       [0.48343203],
       [0.48194418],
       [0.96879522],
       [0.88857396],
       [1.04386864],
       [1.12381385],
       [1.14263336],
       [0.87824751],
       [0.95680876]])