# pytorch_classification

In [88]:
import pandas as pd

df = pd.read_csv('./penguins.csv',index_col=0)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
1  Adelie  Torgersen            39.1           18.7              181.0   
2  Adelie  Torgersen            39.5           17.4              186.0   
3  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen             NaN            NaN                NaN   
5  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  year  
1       3750.0    male  2007  
2       3800.0  female  2007  
3       3250.0  female  2007  
4          NaN     NaN  2007  
5       3450.0  female  2007

In [89]:
df.shape

(344, 8)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 344 entries, 1 to 344
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
 7   year               344 non-null    int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 24.2+ KB


In [91]:
# 결측치 제거
df = df.dropna().reset_index(drop=True)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            333 non-null    object 
 1   island             333 non-null    object 
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object 
 7   year               333 non-null    int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 20.9+ KB


In [93]:
df = df.iloc[:,:-1]
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            36.7           19.3              193.0   
4  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  
0       3750.0    male  
1       3800.0  female  
2       3250.0  female  
3       3450.0  female  
4       3650.0    male

In [94]:
# Convert categorical variable into dummy

island_dummies = pd.get_dummies(df.island)
sex_dummies = pd.get_dummies(df.sex)
island_dummies.head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
3       0      0          1
4       0      0          1

In [95]:
df = pd.concat([df,island_dummies,sex_dummies],axis=1)
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen            36.7           19.3              193.0   
4  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Biscoe  Dream  Torgersen  female  male  
0       3750.0    male       0      0          1       0     1  
1       3800.0  female       0      0          1       1     0  
2       3250.0  female       0      0          1       1     0  
3       3450.0  female       0      0          1       1     0  
4       3650.0    male       0      0          1       0     1

In [96]:
df = df.drop(['island','sex'],axis=1)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
3  Adelie            36.7           19.3              193.0       3450.0   
4  Adelie            39.3           20.6              190.0       3650.0   

   Biscoe  Dream  Torgersen  female  male  
0       0      0          1       0     1  
1       0      0          1       1     0  
2       0      0          1       1     0  
3       0      0          1       1     0  
4       0      0          1       0     1

In [97]:
df.shape

(333, 10)

# Labels

In [98]:
df.species.value_counts()

Adelie       146
Gentoo       119
Chinstrap     68
Name: species, dtype: int64

In [100]:
# 문자열 형태를 정수형으로 변환
def make_int(s):
  if s == 'Adelie':
    return 0
  elif s == 'Gentoo':
    return 1
  else:
    return 2

In [101]:
df['species'] = df['species'].apply(make_int)

In [102]:
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0            39.1           18.7              181.0       3750.0   
1        0            39.5           17.4              186.0       3800.0   
2        0            40.3           18.0              195.0       3250.0   
3        0            36.7           19.3              193.0       3450.0   
4        0            39.3           20.6              190.0       3650.0   

   Biscoe  Dream  Torgersen  female  male  
0       0      0          1       0     1  
1       0      0          1       1     0  
2       0      0          1       1     0  
3       0      0          1       1     0  
4       0      0          1       0     1

# Hold Out

In [103]:
from sklearn.model_selection import train_test_split
import numpy as np

np.set_printoptions(suppress=True)
#I. np.set_printoptions의 suppress option을 True로 설정해 주면 0.11234와 같은 형식으로 출력된다. (fixed point notation)

In [104]:
x = df.iloc[:,1:].values
y = df.iloc[:,0]

In [68]:
x[0],y[0]

(array([  39.1,   18.7,  181. , 3750. ,    0. ,    0. ,    1. ,    0. ,
           1. ]),
 2)

In [105]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1,shuffle=True)
x_train, x_valid, y_train, y_valid = train_test_split(x_train,y_train,test_size=0.1,shuffle=True)

In [106]:
print('Shape of x train : ',x_train.shape)
print('Shape of x test : ',x_test.shape)
print('Shape of x valid : ',x_valid.shape)

print('Shape of y train : ',y_train.shape)
print('Shape of y valid : ',y_valid.shape)
print('Shape of y test : ',y_test.shape)

Shape of x train :  (269, 9)
Shape of x test :  (34, 9)
Shape of x valid :  (30, 9)
Shape of y train :  (269,)
Shape of y valid :  (30,)
Shape of y test :  (34,)


In [107]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train[:,:-5]

array([[  35.1,   19.4,  193. , 4200. ],
       [  48.2,   14.3,  210. , 4600. ],
       [  42.8,   18.5,  195. , 4250. ],
       ...,
       [  39.6,   18.8,  190. , 4600. ],
       [  36.8,   18.5,  193. , 3500. ],
       [  50.9,   17.9,  196. , 3675. ]])

In [108]:
scaler.fit(x_train[:,:-5])

StandardScaler()

In [109]:
x_train_std = scaler.transform(x_train[:,:-5])
x_valid_std = scaler.transform(x_valid[:,:-5])
x_test_std = scaler.transform(x_test[:,:-5])

In [110]:
x_train_std[0]

array([-1.64849341,  1.18511028, -0.56865214, -0.01992647])

In [111]:
x_train_std = np.concatenate([x_train_std,x_train[:,-5:]],axis=1)
x_valid_std = np.concatenate([x_valid_std,x_valid[:,-5:]],axis=1)
x_test_std = np.concatenate([x_test_std,x_test[:,-5:]],axis=1)

In [112]:
x_train_std[0]

array([-1.64849341,  1.18511028, -0.56865214, -0.01992647,  0.        ,
        0.        ,  1.        ,  0.        ,  1.        ])

In [113]:
x_valid_std[0]

array([-0.56432218,  0.92764407, -1.19843568, -0.38333121,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ])

In [114]:
x_test_std[0]

array([-1.53633777, -0.05072754, -0.84855593, -1.04957325,  0.        ,
        0.        ,  1.        ,  1.        ,  0.        ])

# Tensor dataset
Pytorch에서 가중치 학습은 실수형으로 진행됨. 그래서 모든 변수를 실수형으로 바꿔주어야 함.

그리고 ndarray와 호환이 안되기 때문에 torch tensor type으로 변환 필요

In [115]:
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset

In [116]:
x_train_std.dtype

dtype('float64')

In [117]:
x_train_std = torch.tensor(x_train_std,dtype=torch.float32)
x_valid_std = torch.tensor(x_valid_std,dtype=torch.float32)
x_test_std = torch.tensor(x_test_std,dtype=torch.float32)

In [118]:
x_train_std[0]

tensor([-1.6485,  1.1851, -0.5687, -0.0199,  0.0000,  0.0000,  1.0000,  0.0000,
         1.0000])

In [17]:
#np_x =df.iloc[:,1:].to_numpy()
#np_y = df.iloc[:,0].to_numpy()
np_x = df.iloc[:,1:].values
np_y = df.iloc[:,0].values

In [18]:
#numpy 배열로 부터 tensor를 정의 할 수있음 df는 안됨, 숫자 자료형만 넣을 수 있음 object는 안됨
torch_x_np = torch.from_numpy(np_x)
torch_y_np = torch.from_numpy(np_y)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [119]:
y_train = torch.tensor(y_train.values).long()
y_valid = torch.tensor(y_valid.values).long()
y_test = torch.tensor(y_test.values).long()

In [120]:
y_train[0]

tensor(0)

In [121]:
y_test

tensor([0, 0, 0, 1, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 0, 2, 2, 1, 2, 0, 1, 1, 1, 0,
        0, 1, 0, 1, 2, 2, 1, 0, 2, 0])

torch.utils.data.DataLoader 와 torch.utils.data.Dataset 의 두 가지 데이터 기본 요소를 제공하여 미리 준비해둔(pre-loaded) 데이터셋 뿐만 아니라 가지고 있는 데이터를 사용할 수 있도록 합니다.<br> Dataset 은 샘플과 정답(label)을 저장하고, DataLoader 는 Dataset 을 샘플에 쉽게 접근할 수 있도록 순회 가능한 객체(iterable)로 감쌉니다.

In [123]:
# Make dataset
train_dataset = TensorDataset(x_train_std,y_train)
valid_dataset = TensorDataset(x_valid_std,y_valid)
test_dataset = TensorDataset(x_test_std,y_test)

# Make dataloader
trainloader = DataLoader(train_dataset,batch_size=32,shuffle=True)
validloader = DataLoader(valid_dataset,batch_size=4)
testloader = DataLoader(test_dataset,batch_size=4)

In [132]:
# Check data
for x,y in trainloader:
  print(x.shape)
  print()
  print(y.shape)
  break

torch.Size([32, 9])

torch.Size([32])


## Custom dataset
https://tutorials.pytorch.kr/beginner/basics/data_tutorial.html

In [136]:
class CustomDataset(Dataset):

  def __init__(self,x,y):
    self.x = x
    self.y = y

  def __len__(self):
    return len(self.x)

  def __getitem__(self,idx):
    x_value = torch.tensor(self.x[idx],dtype=torch.float32)
    y_value = torch.tensor(self.y[idx]).long()
    return x_value,y_value

In [125]:
y_train

tensor([0, 1, 0, 1, 2, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 2, 2, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2,
        1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 2, 0, 1, 2, 0,
        0, 1, 1, 1, 0, 2, 1, 0, 2, 1, 2, 2, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0,
        1, 1, 0, 1, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0, 0,
        0, 0, 1, 2, 2, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 0,
        2, 0, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 1, 0, 0, 2, 2,
        1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1,
        0, 1, 0, 2, 2, 1, 0, 2, 2, 0, 0, 2, 2, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 2, 0, 0, 2])

In [137]:
train_dataset = CustomDataset(x_train, y_train)
valid_dataset = CustomDataset(x_valid, y_valid)
test_dataset = CustomDataset(x_test, y_test)

In [138]:
# Make dataloader
trainloader = DataLoader(train_dataset,batch_size=32,shuffle=True)
validloader = DataLoader(valid_dataset,batch_size=4)
testloader = DataLoader(test_dataset,batch_size=4)

In [139]:
# Check data
for x,y in trainloader:
  print(x.shape)
  print(y.shape)
  break

torch.Size([32, 9])
torch.Size([32])


C:\Users\jwshi\AppData\Local\Temp\ipykernel_18572\608453465.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_value = torch.tensor(self.y[idx]).long()


# 모형

In [140]:
from torch import nn
from torch import optim

In [141]:
class MyModel(nn.Module):
  #자동으로 bias가 추가?
  def __init__(self):
    super(MyModel,self).__init__()
    #super().__init__()
    self.linear1 = nn.Linear(9,256)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(256,128)
    self.dropout = nn.Dropout(0.2)
    self.out = nn.Linear(128,3)

  def forward(self,x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.relu(x)
    x = self.dropout(x)
    output = self.out(x)
    return output

In [142]:
# GPU 사용 확인
torch.cuda.is_available()

False

In [143]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [144]:
model = MyModel().to(device)
model

MyModel(
  (linear1): Linear(in_features=9, out_features=256, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=256, out_features=128, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
  (out): Linear(in_features=128, out_features=3, bias=True)
)

In [148]:
from torchsummary import summary

In [149]:
summary(model,input_size=(9,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                  [-1, 256]           2,560
              ReLU-2                  [-1, 256]               0
            Linear-3                  [-1, 128]          32,896
              ReLU-4                  [-1, 128]               0
           Dropout-5                  [-1, 128]               0
            Linear-6                    [-1, 3]             387
Total params: 35,843
Trainable params: 35,843
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.01
Params size (MB): 0.14
Estimated Total Size (MB): 0.14
----------------------------------------------------------------


In [150]:
# loss function & opimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [151]:
len(trainloader.dataset)

269

In [152]:
for x, y in trainloader:
  sx = x
  sy = y
  break

C:\Users\jwshi\AppData\Local\Temp\ipykernel_18572\608453465.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_value = torch.tensor(self.y[idx]).long()


In [153]:
sx.shape, y.shape

(torch.Size([32, 9]), torch.Size([32]))

In [154]:
output = model(sx)
output.shape

torch.Size([32, 3])

In [155]:
output[0]

tensor([ -47.6929, -146.2500,   94.9034], grad_fn=<SelectBackward0>)

In [156]:
def train(model, dataloader, loss_fn,optimizer, epoch):
  # model.train()
  print(f'Epoch : {epoch}')
  size = len(dataloader.dataset)
  total_batch = len(dataloader)
  running_loss = 0
  for batch, (X, y) in enumerate(dataloader):
    X = X.to(device)
    y = y.to(device)

    output = model(X)
    loss = loss_fn(output, y)

    optimizer.zero_grad() # 이전 경사 값들의 정보를 날림
    loss.backward()
    optimizer.step()

    print(f'Train loss : {loss.item():>7f} [{batch*len(X)}/{size}]')
    running_loss += loss.item()
  print(f'Average Train loss : {running_loss/total_batch}\n')
  return running_loss

학습 단계(loop)에서 최적화는 세단계로 이뤄집니다:
- optimizer.zero_grad()를 호출하여 모델 매개변수의 변화도를 재설정합니다. 기본적으로 변화도는 더해지기(add up) 때문에 중복 계산을 막기 위해 반복할 때마다 명시적으로 0으로 설정합니다.

- loss.backwards()를 호출하여 예측 손실(prediction loss)을 역전파합니다. PyTorch는 각 매개변수에 대한 손실의 변화도를 저장합니다.

- 변화도를 계산한 뒤에는 optimizer.step()을 호출하여 역전파 단계에서 수집된 변화도로 매개변수를 조정합니다.<br>
https://tutorials.pytorch.kr/beginner/basics/optimization_tutorial.html

In [157]:
for epoch in range(100):
  train(model,trainloader,criterion,optimizer,epoch)

Epoch : 0
Train loss : 80.524750 [0/269]
Train loss : 177.007462 [32/269]
Train loss : 102.845001 [64/269]
Train loss : 110.967430 [96/269]
Train loss : 74.532013 [128/269]
Train loss : 64.908936 [160/269]
Train loss : 138.022522 [192/269]
Train loss : 47.040630 [224/269]
Train loss : 59.495651 [104/269]
Average Train loss : 95.038266075982

Epoch : 1
Train loss : 62.753815 [0/269]
Train loss : 99.653923 [32/269]
Train loss : 55.181713 [64/269]
Train loss : 66.625847 [96/269]
Train loss : 74.287926 [128/269]
Train loss : 70.359627 [160/269]
Train loss : 84.498360 [192/269]
Train loss : 50.412025 [224/269]
Train loss : 49.678955 [104/269]
Average Train loss : 68.16135448879666

Epoch : 2
Train loss : 82.261337 [0/269]
Train loss : 65.372261 [32/269]
Train loss : 53.049046 [64/269]
Train loss : 46.663273 [96/269]
Train loss : 54.837337 [128/269]
Train loss : 54.190273 [160/269]
Train loss : 47.170551 [192/269]
Train loss : 34.237358 [224/269]
Train loss : 50.308403 [104/269]
Average Trai

C:\Users\jwshi\AppData\Local\Temp\ipykernel_18572\608453465.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_value = torch.tensor(self.y[idx]).long()


Train loss : 1.097481 [192/269]
Train loss : 1.095479 [224/269]
Train loss : 1.064803 [104/269]
Average Train loss : 1.0913909541236029

Epoch : 9
Train loss : 1.068471 [0/269]
Train loss : 1.086928 [32/269]
Train loss : 1.102236 [64/269]
Train loss : 1.080157 [96/269]
Train loss : 1.080778 [128/269]
Train loss : 1.117508 [160/269]
Train loss : 1.102321 [192/269]
Train loss : 1.091990 [224/269]
Train loss : 1.106469 [104/269]
Average Train loss : 1.0929841068055894

Epoch : 10
Train loss : 1.098578 [0/269]
Train loss : 1.078167 [32/269]
Train loss : 1.113272 [64/269]
Train loss : 1.084755 [96/269]
Train loss : 1.104330 [128/269]
Train loss : 1.083030 [160/269]
Train loss : 1.090890 [192/269]
Train loss : 1.071972 [224/269]
Train loss : 1.088188 [104/269]
Average Train loss : 1.090353594885932

Epoch : 11
Train loss : 1.089075 [0/269]
Train loss : 1.105448 [32/269]
Train loss : 1.093896 [64/269]
Train loss : 1.102589 [96/269]
Train loss : 1.066933 [128/269]
Train loss : 1.090827 [160/26

In [163]:
sx

tensor([[4.1500e+01, 1.8300e+01, 1.9500e+02, 4.3000e+03, 0.0000e+00, 0.0000e+00,
         1.0000e+00, 0.0000e+00, 1.0000e+00],
        [3.9600e+01, 1.8800e+01, 1.9000e+02, 4.6000e+03, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0000e+00],
        [5.8000e+01, 1.7800e+01, 1.8100e+02, 3.7000e+03, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00],
        [4.2400e+01, 1.7300e+01, 1.8100e+02, 3.6000e+03, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00],
        [4.6300e+01, 1.5800e+01, 2.1500e+02, 5.0500e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0000e+00],
        [4.6700e+01, 1.5300e+01, 2.1900e+02, 5.2000e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0000e+00],
        [4.6200e+01, 1.4500e+01, 2.0900e+02, 4.8000e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00],
        [3.6900e+01, 1.8600e+01, 1.8900e+02, 3.5000e+03, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 1.0000e+0

In [164]:
output = model(sx)

In [170]:
output

tensor([[ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
        [ 0.3030,  0.1270, -0.4122],
 

In [165]:
output[0]

tensor([ 0.3030,  0.1270, -0.4122], grad_fn=<SelectBackward0>)

In [160]:
torch.argmax(output[0])

tensor(0)

In [169]:
output.argmax(dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

In [171]:
(output.argmax(1) == sy).sum().item()

11

In [172]:
def test(model, dataloader, loss_fn,epoch):
  total_batch = len(dataloader)
  size = len(dataloader.dataset)
  model.eval()
  test_loss, correct = 0, 0
  # 경사 계산 X
  with torch.no_grad():

    for X,y in dataloader:
      X = X.to(device)
      y = y.to(device)

      preds = model(X)
      loss = loss_fn(preds,y)
      correct += (preds.argmax(1) == y).sum().item()
      test_loss += loss.item()

    test_loss /= total_batch
    correct /= size

  print(f'Epoch : {epoch} Test Loss : {test_loss}, Test Accuracy : {correct}')

  return test_loss


In [173]:
test(model, validloader, criterion,1)

Epoch : 1 Test Loss : 1.117879942059517, Test Accuracy : 0.4


C:\Users\jwshi\AppData\Local\Temp\ipykernel_18572\608453465.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_value = torch.tensor(self.y[idx]).long()


1.117879942059517