In [1]:
import numpy as np

In [2]:
A = np.arange(2*3*4).reshape((2,3,4)) # 2channel 3rows 4columns
B = np.arange(2*3*4).reshape((2,4,3)) # 2 channel 4rows 3 columns
print(np.dot(A,B).shape)
print(np.matmul(A,B).shape)

(2, 3, 2, 3)
(2, 3, 3)


In [16]:
print(A,A.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [17]:
print(B,B.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] (2, 4, 3)


In [12]:
dot_ab =np.dot(A,B)
print(dot_ab, dot_ab.shape)
'''
0*0 + 1*3 + 2*6 + 3*9 = 46 , 0*1 + 1*4 + 2*7 + 3*10 = 48 , 0*2 + 1*5 + 2*8 + 3*11 =53
4*0 + 5*3 + 6*6 + 7*9 = 114, 


'''

[[[[  42   48   54]
   [ 114  120  126]]

  [[ 114  136  158]
   [ 378  400  422]]

  [[ 186  224  262]
   [ 642  680  718]]]


 [[[ 258  312  366]
   [ 906  960 1014]]

  [[ 330  400  470]
   [1170 1240 1310]]

  [[ 402  488  574]
   [1434 1520 1606]]]] (2, 3, 2, 3)


np.dot(A,B)[i,j,k,m] == np.sum(A[i,j,:] * B[k,:,m])

In [18]:
print(A,A.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [19]:
print(B,B.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] (2, 4, 3)


In [13]:
matmul_ab=np.matmul(A,B)
print(matmul_ab,matmul_ab.shape)

[[[  42   48   54]
  [ 114  136  158]
  [ 186  224  262]]

 [[ 906  960 1014]
  [1170 1240 1310]
  [1434 1520 1606]]] (2, 3, 3)
